### ISSUE TITLE
Show Help in widget does not work (on macOS?)

### ISSUE THREAD

**Issue by kaimikael** [biolab/orange-widget-base#263] opened 2023-12-18 15:04 UTC
##### Orange version

3.36.2, running under macOS 14.1.1

##### Expected behavior
If I click on the "?" (Show Help) icon on a widget, I expect a popup window with documentation for the object.

##### Actual behavior
Nothing happens.

##### Steps to reproduce the behavior
Add a widget to the canvas.
Double-click the widget to open it.
Click the "?" icon in the bottow left corner.
Nothing happens.

**Comment by wvdvegte** [comment] 2023-12-21 13:35
This is a duplicate of [#6609 in orange3](https://github.com/biolab/orange3/issues/6609). It doesn't seem limited to Macs.

**Comment by matt-wombat** [comment] 2024-01-01 15:54
I am having this issue on two Windows 11 machines too. 
Pressing F1-Button does not seem to have any effect as well.
My environment:

Windows 11 version 22H2 Build 22621.28161
Orange 3.36.1 for Windows installed via standalone installer with Miniconda 64 bit from https://orangedatamining.com/download/
Not sure if relevant: My default web browser is ungoogled-chromium 109

**Comment by PrimozGodec** [comment] 2024-02-09 08:14
I think it is solved: https://github.com/biolab/orange3/issues/6609. Feel free to reopen if the error persists.

**Closed by PrimozGodec** 2024-02-09 08:14 UTC
