### ISSUE TITLE
gui.TabWidget renders poorly

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange-widget-base#161] opened 2021-07-02 12:25 UTC
##### Orange version

3.30.dev

##### Expected behavior
gui.TabWidget has no overlapping blue part and not redundant top space.

##### Actual behavior
gui.TabWidget has space on top (not sure this is related to the element, but I remember box=None parameter elsewhere). But a more important issue is the strange blue part that overlaps with the unselected tab.

<img width="462" alt="Screen Shot 2021-07-02 at 14 20 36" src="https://user-images.githubusercontent.com/12524972/124274197-41e7ce80-db41-11eb-959b-ef29c7f61a2d.png">

##### Steps to reproduce the behavior
Place Network Analysis widget on the canvas.

**Comment by janezd** [comment] 2021-09-30 19:34
I'm not sure we can do anything here. `gui.tabWidget` just creates `QTabWidget` and adds it to the layout; it's all in Qt. (See https://github.com/biolab/orange-widget-base/blob/master/orangewidget/gui.py#L2662)

It looks OK on my machine (Catalina, Qt 5.15). Which Qt do you have?

**Comment by ajdapretnar** [comment] 2021-10-01 07:55
Apparently, Qt 5.15 is not yet available on conda and I would hate to destroy my environment with some pip installations. It is not such a big issue, we can close it if you wish.

**Comment by janezd** [comment] 2021-10-01 18:01
Anybody else can reproduce it? On Qt 5.15 maybe?

**Comment by markotoplak** [comment] 2021-10-01 20:06
@ajdapretnar, is there also a problem with the dmg? The previous version had Qt 5.12 and the last one is on Qt 5.15. This might be the easiest way to test without changing anything in your dev environments.

Also, if not even the 3.29.3 dmg does not exhibit this problem, this means that Qt in your conda environment is already kinda destroyed. :)

**Comment by janezd** [comment] 2021-10-01 21:20
> Also, if not even the 3.29.3 dmg does not exhibit this problem, this means that Qt in your conda environment is already kinda destroyed. 

, which we already know is the case. Her qt has always been weird. :)

**Comment by janezd** [comment] 2022-08-23 10:08
@ajdapretnar, can we close this one?

**Comment by ajdapretnar** [comment] 2022-08-23 11:18
Do we want to close this because we don't like seeing the issue or because it was fixed? 😅 
Because the issue remains. `PyQt5==5.15.6`

<img width="335" alt="Screenshot 2022-08-23 at 13 15 39" src="https://user-images.githubusercontent.com/12524972/186144698-124d2b0f-e3ef-407b-af98-d5d84bbff49f.png">

**Comment by janezd** [comment] 2022-08-23 12:15
Because we wouldn't like to see it if it is fixed. :)

Or ... if we there's nothing we can do about it. I checked: this is a [Qt bug](https://bugreports.qt.io/browse/QTBUG-86513), which has been fixed. Bad rendering will disappear when we move to newer versions of Qt.

**Closed by janezd** 2022-08-23 12:15 UTC
